### ISSUE TITLE
NoClassDefFoundError: net/dark_roleplay/drpcore/api/old/modules/materials/AddResourceGenerators

### ISSUE THREAD

**Issue by vinz243** [DarkRoleplay/Dark-Roleplay-Medieval#15]
Trying latest version (built from cb560c7099221b53e31fa3f5de6d4ce912bd0edc on 1.12 branch) with drpcore 0.3.5e, I get this error when starting mc:

```

[01:15:13] [main/ERROR] [FML/]: Caught exception from drpmedieval (Dark Roleplay Medieval)
net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/dark_roleplay/drpcore/api/old/modules/materials/AddResourceGenerators

	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89) ~[forge-1.12.2-14.23.2.2611.jar:?]
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:584) ~[forge-1.12.2-14.23.2.2611.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:231) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/dark_roleplay/drpcore/api/old/modules/materials/AddResourceGenerators
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693) ~[?:1.8.0_25]
	at java.lang.Class.privateGetPublicMethods(Class.java:2894) ~[?:1.8.0_25]
	at java.lang.Class.getMethods(Class.java:1607) ~[?:1.8.0_25]
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:81) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82) ~[AutomaticEventSubscriber.class:?]
	... 37 more
Caused by: java.lang.ClassNotFoundException: net.dark_roleplay.drpcore.api.old.modules.materials.AddResourceGenerators
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693) ~[?:1.8.0_25]
	at java.lang.Class.privateGetPublicMethods(Class.java:2894) ~[?:1.8.0_25]
	at java.lang.Class.getMethods(Class.java:1607) ~[?:1.8.0_25]
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:81) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82) ~[AutomaticEventSubscriber.class:?]
	... 37 more
Caused by: java.lang.NullPointerException
```

Thanks

**Comment by JTK222** [comment]
Hm.... could you send me your fml-client-latest.log? It seems like the Core Mod either isn't loaded, you use a wrong version or it's loaded in the wrong order (what it shouldn't)

**Comment by vinz243** [comment]
Here you go [fml-client-3.log](https://github.com/DarkRoleplay/Dark-Roleplay-Medieval/files/2010492/fml-client-3.log)

**Comment by JTK222** [comment]
Due to the log you have the wrong version (v 0.3.5) and not 0.3.5e if updating doesn't work I will take a closer look at that.

**Comment by vinz243** [comment]
With 0.3.5e i get a CTD after startup 
[fml-client-latest.log](https://github.com/DarkRoleplay/Dark-Roleplay-Medieval/files/2014152/fml-client-latest.log)

**Comment by JTK222** [comment]
Hm.... strange... but one question... why does your DRPMedieval Mod Jar the version 0.2.5? I've not released that version, and the latest version is 0.2.4c/0.2.4.3.

In each case I will take a closer look at this.

**Comment by vinz243** [comment]
I wasn't able to download your mod from curseforge, even though it was written lat updated in may the latest version was still from feb so I had to build it myself

**Comment by JTK222** [comment]
So there is your problem.
The latest version is from February... there were no other releases.
If you want to use unstable stuff, do it properly, I am not going to support stuff that you shouldn't touch.
In other words, this is closed.

**Comment by vinz243** [comment]
Thank you very much ! I tried to run it without success unfortunately see #16
