### ISSUE TITLE
ClassNotFoundException: net.dark_roleplay.core_modules.crops.configs.Crops

### ISSUE THREAD

**Issue by vinz243** [DarkRoleplay/Dark-Roleplay-Medieval#16]
Hi,

I tried to build both drplibrary and drpcmcrops from the Github repos, and got the error I attached

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Dark Roleplay Core Module Dates (drpcmdates)
Caused by: net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: net.dark_roleplay.core_modules.crops.configs.Crops
	at net.minecraftforge.common.config.ConfigManager.sync(ConfigManager.java:191)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:585)
```

But I do have the library:

```
 UE    | drpcmdates           | 1.12.2-1.1.1             | drpcmdates-1.12.2-1.0.0.jar                   | 893c317856cf6819b3a8381c566
```

And the .class is in the jar file.

[crash-2018-08-01_22.58.13-client.txt](https://github.com/DarkRoleplay/Dark-Roleplay-Medieval/files/2251127/crash-2018-08-01_22.58.13-client.txt)

**Comment by JTK222** [comment]
o_O b.... b... but how the he... Why could I compile the mod when others do have problems with it O-o did I forget to commit something :sob:
Oh wait a second :thinking: is it fixed if you delete the old config files if you had any previously? That would explain why it didn't appear in dev.

**Comment by JTK222** [comment]
So, first point I am not supposed to give any support regarding self built versions of the mod.
Therefore I will close this issue.
I am not ensuring that it's compileable after a commit, and I am not going to try.
When it works it's just a happy cooinsidence. 

However it seems that you are using wrong branches for building. If there is a 1.12 branch that's the one you want to use, if not then the master branch.

**Comment by vinz243** [comment]
I understand you don't wanna support selfbuilt versions but I had to build because I could not find drplibrary and drpcmcrops. Anyway you may wanna use git tag to mark working versions once you built it and you know it works. I will try again and check the branches

**Comment by JTK222** [comment]
You aren't supposed to use DRPLibrary or DRPCrops at all.
It's not released as a built file for a reason. 
The stuff you need to use my mods are bundled within DRPCore.
As the licenses are All Rights reserved (the default if no License is selected) there is no need to mark any working stuff. The mod is **visible** Source **not** open source.

All files that you really need can be found here: https://minecraft.curseforge.com/members/JTK222/projects
Even though everything that's released besides the Core and Medieval part are just in favour of lazy modpack creators.

**Comment by vinz243** [comment]
I am not redistributing it"s only to try and make it work... Here is the lo with only last two jars:

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 8/3/18 1:23 AM
Description: Initializing game

java.lang.NoClassDefFoundError: Lnet/dark_roleplay/core_modules/crops/api/blocks/Crop;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.privateGetPublicFields(Class.java:2614)
	at java.lang.Class.getFields(Class.java:1557)
	at net.minecraftforge.registries.ObjectHolderRegistry.scanClassForFields(ObjectHolderRegistry.java:145)
	at net.minecraftforge.registries.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:115)
	at net.minecraftforge.registries.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:68)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:599)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.dark_roleplay.core_modules.crops.api.blocks.Crop
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.privateGetPublicFields(Class.java:2614)
	at java.lang.Class.getFields(Class.java:1557)
	at net.minecraftforge.registries.ObjectHolderRegistry.scanClassForFields(ObjectHolderRegistry.java:145)
	at net.minecraftforge.registries.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:115)
	at net.minecraftforge.registries.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:68)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:599)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 361792016 bytes (345 MB) / 603979776 bytes (576 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID          | Version      | Source                          | Signature                                |
	|:----- |:----------- |:------------ |:------------------------------- |:---------------------------------------- |
	| UC    | minecraft   | 1.12.2       | minecraft.jar                   | None                                     |
	| UC    | mcp         | 9.42         | minecraft.jar                   | None                                     |
	| UC    | FML         | 8.0.99.99    | forge-1.12.2-14.23.2.2611.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge       | 14.23.2.2611 | forge-1.12.2-14.23.2.2611.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | drpcore     | 0.4.3        | drpcore-1.12.2-0.4.3(1).jar     | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| UC    | drpmedieval | 0.2.5        | drpmedieval-1.12.2-0.2.5(1).jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.2.2611
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: BitBetter+MC12+OPT+4.0.6.zip, 128x Better Foliage Textures.zip, 128x GUI.zip, 128x Environment.zip, 128x Optifine Textures.zip, 128x Optifine Textures - Continuum 2.0 Addon.zip, 128x Block Textures.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
****
```

**Comment by JTK222** [comment]
So far it doesn't seem like you tried to make it work. You are just sending me crash logs that others already sent me. If you really want to help, then stop trying to build stuff on your own, use the files all other also get access to and report bugs and crashes that you find.

**Comment by vinz243** [comment]
That's what I did with the last message. I only used the two latest downloadable versions of drpcore and drpmedieval. This is the crash I get when I with a clean .minecraft, removed all the files inside and installed 1.12 + forge then only `drpcore-1.12.2-0.4.3` and `drpmedieval-1.12.2-0.2.5`

**Comment by JTK222** [comment]
I found the issue, it seems that something that wasn't supposed to happen, happened.
(It removed an entire class while building, even though it shouldn't have been removed)
Either build the crops thingy yourself or get it from the snapshots channel in our discord.dark-roleplay.net I can't release it on curse right now.

**Comment by vinz243** [comment]
It's working now awesome thank you!
