### ISSUE TITLE
Crash right clicking Oak Crate

### ISSUE THREAD

**Issue by OreCruncher** [DarkRoleplay/Dark-Roleplay-Medieval#20]
Forge: 14.23.5.2773
DRP: 0.3.0.1
DRP Core: 0.4.6.2

Found a house in a village and right clicked an Oak Crate that was there.  Server side crashed:

```
[10:12:49] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Slot 1 not in valid range - [0,1)
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.RuntimeException: Slot 1 not in valid range - [0,1)
	at net.minecraftforge.items.ItemStackHandler.validateSlotIndex(ItemStackHandler.java:214) ~[ItemStackHandler.class:?]
	at net.minecraftforge.items.ItemStackHandler.getStackInSlot(ItemStackHandler.java:73) ~[ItemStackHandler.class:?]
	at net.minecraftforge.items.SlotItemHandler.func_75211_c(SlotItemHandler.java:73) ~[SlotItemHandler.class:?]
	at net.minecraft.inventory.Container.func_75138_a(Container.java:63) ~[afr.class:?]
	at net.minecraft.inventory.Container.func_75132_a(Container.java:52) ~[afr.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:101) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) ~[aed.class:?]
	at net.dark_roleplay.medieval.common.objects.blocks.behaviors.Behavior_Container.execute(Behavior_Container.java:55) ~[Behavior_Container.class:?]
	at net.dark_roleplay.library.experimental.blocks.DRPBlock.func_180639_a(DRPBlock.java:133) ~[DRPBlock.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:449) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```

**Comment by JTK222** [comment]
Yeah, I need to remove the village building/update them.
The save format has slightly changed and it assumes that the slot amount is one, which isn't true and causes a crash.

**Comment by JTK222** [comment]
Fixed in version 0.3.1 (only affects new buildings)
Still need to fix it for already existing villager buildings
